### ISSUE TITLE
GIF support?

### ISSUE THREAD

**Issue by mre** [kornelski/cavif#4]
Thanks for the tool @kornelski. I'm currently integrating it into my blog's CI.
I wonder if you plan to add animation support to cavif eventually.
This would help replace the gifs on my blog with avif as well (using gif as a fallback only).

**Comment by kornelski** [comment]
I do not plan to ever support it. AVIF-sequence is a separate format from AVIF. They even have two different MIME types.

The biggest problem is that AVIF-sequence, like all "GIF killers", is *incredibly inefficient and slow*:

https://bugs.chromium.org/p/chromium/issues/detail?id=1124084&q=avif&can=2

Inefficiency of AVIF-s brings Chrome to its knees, and that bug will be "fixed" by eating all your RAM instead. 

It's an [inherent design failure of all "animation" formats](https://kornel.ski/efficient-gifs) (GIF, APNG, AWebP and AVIFs all alike) that they have GIF-like primitive frames layered on top of each other with no guaranteed keyframes. Because of that browsers are forced to choose between:

* Re-decoding the entire animation from the beginning of the file every time they need to seek/rewind the animation. And they need to do this when scrolling the page or switching between tabs.

* Cache the whole *uncompressed* animation in memory. It eats tons of RAM. Uncompressed RGBA bitmaps take literally 100 times more memory than the file size of the animation file.

All "animation" formats have lousy compression and are waste of bandwidth. In order to turn "video" into "animation" they drop all of the most efficient codec features, such as predicted frames and motion vectors. This makes them all barely smaller than GIF. Removal of the most efficient compression features throws more work at entropy coding, which is a slow single-threaded parts of codecs. Toy formats typically also don't get hardware decoding acceleration any more, so you get larger files, and even more CPU work to decode them.


Forget about all GIF-equivalent formats. Instead, embed a real AV1 video, or H.264 or VP9 in a `<video autoplay loop muted playsinline>` tag. That will give you greater bandwidth savings (by a factor larger than going from GIF to another GIF-like format), and will be much easier on browsers thanks to keyframes and hardware acceleration.

I know the `<video>` tag is a hassle. Huge props to [Safari that supports efficient hw-accelerated H.264 MP4 directly in `<img>` tag](https://calendar.perfplanet.com/2017/animated-gif-without-the-gif/). Blink needs to catch up, so that we can stop making awful "animation" formats to work around Blink's technical limitations.

**Comment by mre** [comment]
I see. Thanks for the thorough explanation. In this case I won't handle this case in my image pipeline for now as it requires some bigger changes to move from gif to video. The two little pet-peeves I have with video are that some platforms don't support auto-play (e.g. Github `README` files) and they cannot be easily copied straight from the browser (except in Safari, I guess).
But you already touched on that, so I think we can close this.
